# Generated by Django 5.2.10 on 2026-01-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='admission_number_format',
            field=models.CharField(choices=[('YEAR_SEQ', 'Year + Sequential (2026-0001)'), ('PREFIX_YEAR_SEQ', 'Prefix + Year + Sequential (ABC-2026-0001)'), ('CUSTOM', 'Manual entry (admin enters number)')], default='YEAR_SEQ', help_text='How admission/application numbers should be generated for this school', max_length=20, verbose_name='Admission Number Format'),
        ),
        migrations.AddField(
            model_name='school',
            name='admission_prefix',
            field=models.CharField(blank=True, help_text="Optional prefix (e.g. 'KCB-', 'INT-', 'SCH-'). Only used if format includes prefix.", max_length=20, verbose_name='Admission Number Prefix'),
        ),
        migrations.AddField(
            model_name='school',
            name='admission_seq_padding',
            field=models.PositiveSmallIntegerField(default=4, help_text='Number of digits for the sequential part (e.g. 4 → 0001, 5 → 00001)', verbose_name='Sequence Number Padding'),
        ),
    ]
