# Generated by Django 6.0 on 2026-01-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='official_registration_number',
            field=models.CharField(blank=True, help_text="Enter the official registration number issued by your country's education authority (MOE, KNEC, State Board, etc.)", max_length=100, null=True, verbose_name='Official Registration / Licence Number'),
        ),
        migrations.AddField(
            model_name='school',
            name='registration_authority',
            field=models.CharField(blank=True, help_text='e.g. Ministry of Education, State Board of Education, Private Schools Regulatory Authority, etc.', max_length=100, null=True, verbose_name='Issuing Authority'),
        ),
        migrations.AddField(
            model_name='school',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Registration Date'),
        ),
    ]
