# Generated by Django 5.2.10 on 2026-01-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_admission_number_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='admission_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default admission fee amount for new applications (can be overridden per application)', max_digits=10, verbose_name='Standard Admission Fee'),
        ),
    ]
