# Generated by Django 5.2.10 on 2026-01-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_school_admission_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='admission_fee',
        ),
    ]
