# Generated by Django 5.2.10 on 2026-01-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_school_admission_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from name (used in public URLs)', max_length=100, null=True, unique=True),
        ),
    ]
