# Generated by Django 5.2.10 on 2026-02-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_school_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='academic_year_end_month',
            field=models.CharField(default='December', help_text='End month of academic year', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='academic_year_start_month',
            field=models.CharField(default='January', help_text='Start month of academic year', max_length=20),
        ),
    ]
