# Generated by Django 5.2.10 on 2026-01-21 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_initial'),
        ('students', '0003_student_allergies_student_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergy_records', to='students.student'),
        ),
    ]
