# Generated by Django 6.0 on 2026-01-09 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_categories', to='school.school')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('frequency', models.CharField(choices=[('per_term', 'Per Term'), ('per_year', 'Per Year'), ('one_time', 'One-time'), ('monthly', 'Monthly')], default='per_term', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.feecategory')),
                ('departments', models.ManyToManyField(blank=True, related_name='applicable_fees', to='academics.department')),
                ('grade_levels', models.ManyToManyField(blank=True, related_name='applicable_fees', to='academics.gradelevel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
