# Generated by Django 5.2.10 on 2026-02-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin / Owner'), ('SCHOOL_ADMIN', 'School Administrator'), ('PRINCIPAL', 'Principal / Head Teacher'), ('DEPUTY_PRINCIPAL', 'Deputy Principal / Vice Principal'), ('ADMISSIONS_OFFICER', 'Admissions Officer / Registrar'), ('ACCOUNTANT', 'Accountant / Bursar'), ('ACADEMIC_COORDINATOR', 'Academic Coordinator / Head of Section'), ('TEACHER', 'Teacher'), ('LIBRARIAN', 'Librarian'), ('PARENT', 'Parent'), ('STUDENT', 'Student')], default='SUPER_ADMIN', max_length=30),
        ),
    ]
