# Generated by Django 5.2.10 on 2026-02-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_change_password',
            field=models.BooleanField(default=False, help_text='User must change password on next login'),
        ),
    ]
