# Generated by Django 5.2.10 on 2026-01-19 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('school', '0004_remove_school_admission_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='is_template',
            field=models.BooleanField(default=False, help_text='True if this is a global template (school should be null)'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='school.school'),
        ),
        migrations.AlterField(
            model_name='department',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='school.school'),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_levels', to='school.school'),
        ),
        migrations.AddConstraint(
            model_name='curriculum',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_template', True), ('school__isnull', True)), models.Q(('is_template', False), ('school__isnull', False)), _connector='OR'), name='template_school_consistency'),
        ),
    ]
