# Generated by Django 5.2.10 on 2026-01-19 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_curriculum_is_template_alter_curriculum_school_and_more'),
        ('school', '0004_remove_school_admission_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'ordering': ['-is_template', 'name']},
        ),
        migrations.RemoveConstraint(
            model_name='curriculum',
            name='template_school_consistency',
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='gradelevel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Null for global templates', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='school.school'),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_levels', to='academics.curriculum'),
        ),
        migrations.AddConstraint(
            model_name='curriculum',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_template', True), ('school__isnull', True)), models.Q(('is_template', False), ('school__isnull', False)), _connector='OR'), name='curriculum_template_school_consistency'),
        ),
        migrations.AddConstraint(
            model_name='curriculum',
            constraint=models.UniqueConstraint(condition=models.Q(('school__isnull', False)), fields=('school', 'name'), name='curriculum_unique_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='curriculum',
            constraint=models.UniqueConstraint(condition=models.Q(('is_template', True), ('school__isnull', True)), fields=('name',), name='curriculum_unique_template_name'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('school__isnull', False)), fields=('school', 'name'), name='department_unique_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='gradelevel',
            constraint=models.UniqueConstraint(condition=models.Q(('school__isnull', False)), fields=('school', 'name'), name='gradelevel_unique_name_per_school'),
        ),
    ]
