# Generated by Django 5.2.10 on 2026-01-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_curriculum_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradelevel',
            name='education_level',
            field=models.CharField(blank=True, choices=[('PRE_PRIMARY', 'Pre-Primary / Kindergarten'), ('ELEMENTARY', 'Elementary / Primary'), ('MIDDLE', 'Middle / Junior Secondary'), ('HIGH', 'High / Senior Secondary'), ('OTHER', 'Other / Vocational / Special')], default='ELEMENTARY', help_text='Used for conditional logic in admissions, reports, etc.', max_length=20),
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='pathway',
            field=models.CharField(blank=True, choices=[('GENERAL', 'General / No Pathway'), ('STEM', 'STEM / Sciences'), ('ARTS', 'Arts / Humanities'), ('VOCATIONAL', 'Vocational / TVET'), ('OTHER', 'Other / Custom')], default='GENERAL', help_text='Optional – used for senior secondary pathways, streams, etc.', max_length=20),
        ),
    ]
