# Generated by Django 5.2.10 on 2026-01-17 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumni', '0001_initial'),
        ('events', '0001_initial'),
        ('school', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnus',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumni_record', to='students.student'),
        ),
        migrations.AddField(
            model_name='donation',
            name='alumnus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumni.alumnus'),
        ),
        migrations.AddField(
            model_name='donation',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='school.school'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='alumnus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.alumnus'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_event_attendance', to='school.school'),
        ),
    ]
