# Generated by Django 5.2.10 on 2026-01-17 15:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('alumni', '0001_initial'),
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('has_pickup_permission', models.BooleanField(default=False)),
                ('has_legal_custody', models.BooleanField(default=False)),
                ('preferred_contact_method', models.CharField(choices=[('PHONE', 'Phone'), ('EMAIL', 'Email'), ('SMS', 'SMS')], default='PHONE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('relationship', models.CharField(blank=True, choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('GUARDIAN', 'Guardian'), ('OTHER', 'Other')], max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_guardians', to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('genotype', models.CharField(blank=True, max_length=5)),
                ('allergies', models.TextField(blank=True)),
                ('chronic_conditions', models.TextField(blank=True)),
                ('disabilities', models.TextField(blank=True)),
                ('medication', models.TextField(blank=True)),
                ('medication_instructions', models.TextField(blank=True)),
                ('emergency_notes', models.TextField(blank=True)),
                ('emergency_doctor', models.CharField(blank=True, max_length=255)),
                ('preferred_hospital', models.CharField(blank=True, max_length=255)),
                ('immunization_status', models.CharField(choices=[('UP_TO_DATE', 'Up to date'), ('PARTIAL', 'Partial'), ('NOT_IMMUNIZED', 'Not immunized'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('immunization_notes', models.TextField(blank=True)),
                ('consent_to_treat', models.BooleanField(default=False)),
                ('medical_disclosure_allowed', models.BooleanField(default=False)),
                ('consent_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_consents', to='students.guardian')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records_recorded', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records_reviewed', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_medical_records', to='school.school')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='medical_documents/')),
                ('document_type', models.CharField(choices=[('VACCINATION_CARD', 'Vaccination Card'), ('MEDICAL_REPORT', 'Medical Report'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_number', models.CharField(max_length=50, unique=True)),
                ('upi_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('nemis_id', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(default='Kenyan', max_length=50)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('stream', models.CharField(blank=True, max_length=50)),
                ('boarding_status', models.CharField(choices=[('DAY', 'Day'), ('BOARDING', 'Boarding'), ('MIXED', 'Mixed')], default='DAY', max_length=20)),
                ('special_needs', models.TextField(blank=True)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('fee_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('scholarship', models.BooleanField(default=False)),
                ('bursary_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('GRADUATED', 'Graduated'), ('TRANSFERRED', 'Transferred'), ('SUSPENDED', 'Suspended'), ('EXPELLED', 'Expelled')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumni', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to='alumni.alumnus')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_created', to=settings.AUTH_USER_MODEL)),
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.gradelevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.school')),
            ],
            options={
                'ordering': ['admission_number'],
            },
        ),
    ]
