# Generated by Django 5.2.10 on 2026-01-17 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='transport_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='transport.studentassignment'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_medical_record', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.guardian'),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['phone'], name='students_gu_phone_a1a96b_idx'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['email'], name='students_gu_email_97bf2f_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'status'], name='students_st_school__332118_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'current_class'], name='students_st_school__8615d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('school', 'admission_number')},
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['school', 'student'], name='students_me_school__22efa1_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['immunization_status'], name='students_me_immuniz_2392c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentguardian',
            unique_together={('student', 'guardian')},
        ),
    ]
