# Generated by Django 6.0 on 2026-01-02 04:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='relationship',
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='has_legal_custody',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='has_pickup_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='is_emergency_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='preferred_contact_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='relationship',
            field=models.CharField(default='OTHER', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
