# Generated by Django 6.0 on 2026-01-04 09:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_guardian_relationship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guardian',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardian',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='guardian',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['phone'], name='students_gu_phone_a1a96b_idx'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['email'], name='students_gu_email_97bf2f_idx'),
        ),
    ]
