# Generated by Django 5.2.10 on 2026-01-17 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_initial'),
        ('school', '0002_school_admission_number_format_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='parent_email',
            new_name='primary_guardian_email',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='parent_name',
            new_name='primary_guardian_name',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='parent_phone',
            new_name='primary_guardian_phone',
        ),
        migrations.AddField(
            model_name='application',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='primary_guardian_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_applications', to='school.school'),
        ),
        migrations.AddField(
            model_name='application',
            name='sub_county',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
