# Generated by Django 5.2.10 on 2026-01-17 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_rename_parent_email_application_primary_guardian_email_and_more'),
        ('school', '0002_school_admission_number_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_applications', to='school.school'),
        ),
    ]
