# Generated by Django 5.2.10 on 2026-01-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_alter_application_middle_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='county',
        ),
        migrations.RemoveField(
            model_name='application',
            name='sub_county',
        ),
        migrations.AddField(
            model_name='application',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='application',
            name='chronic_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='disability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='emergency_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='entry_exam_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Entry / National Exam ID'),
        ),
        migrations.AddField(
            model_name='application',
            name='entry_exam_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='learner_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Learner ID / Student Number'),
        ),
        migrations.AddField(
            model_name='application',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='admission_photos/'),
        ),
        migrations.AddField(
            model_name='application',
            name='placement_type',
            field=models.CharField(choices=[('SELF', 'Self / Parent Application'), ('PUBLIC', 'Government / Public Authority Placement'), ('TRANSFER', 'Transfer from Another School'), ('OTHER', 'Other (e.g. scholarship, international)')], default='SELF', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='primary_guardian_id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
