# Generated by Django 5.2.10 on 2026-01-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_application_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='admission_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
