# Generated by Django 5.2.10 on 2026-01-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_application_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='checksum',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='applicationdocument',
            constraint=models.UniqueConstraint(fields=('application', 'checksum'), name='unique_document_per_application'),
        ),
    ]
