# Generated by Django 5.2.10 on 2026-01-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_applicationdocument_checksum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='checksum',
            field=models.CharField(default='temp', editable=False, max_length=64),
        ),
    ]
