# Generated by Django 5.2.10 on 2026-02-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0010_alter_applicationdocument_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='resume_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='checksum',
            field=models.CharField(editable=False, max_length=64),
        ),
    ]
