# Generated by Django 5.2.10 on 2026-02-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_application_resume_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume_token',
        ),
        migrations.RemoveField(
            model_name='application',
            name='resume_token_expires',
        ),
        migrations.AddField(
            model_name='application',
            name='interview_contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_venue',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
