# Generated by Django 5.2.10 on 2026-02-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_remove_application_resume_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_outcome',
            field=models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('WAITLIST', 'Waitlist'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
