# Generated by Django 5.2.10 on 2026-02-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0013_application_interview_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interviewer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
