# Generated by Django 5.2.10 on 2026-02-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0014_application_interview_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('TEST_SCHEDULED', 'Test Scheduled'), ('OFFERED', 'Offered'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('ENROLLED', 'Enrolled'), ('INTERVIEW_COMPLETED', 'Interview Completed')], default='DRAFT', max_length=20),
        ),
    ]
